$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
name: train_lr
display_name: Train Logistic Regression
type: command
inputs:
  train:
    type: uri_file
outputs:
  model_dir:
    type: uri_folder
code: .
environment:
  image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:latest
  conda_file: ../../envs/conda.yml
command: >-
  python train_lr.py
  --train ${{inputs.train}}
  --model_dir ${{outputs.model_dir}}
