name: heart-mlops
channels: [conda-forge, defaults]
dependencies:
  - python=3.10
  - pip
  - pip:
      - azure-ai-ml
      - azure-identity
      - azureml-mlflow
      - pandas
      - numpy
      - scikit-learn
      - matplotlib
