name: dropout_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - pandas==2.2.2
      - numpy==1.26.4
      - scikit-learn==1.3.2           # ✅ compatible con imblearn
      - joblib==1.4.2
      - mlflow==2.16.2
      - azure-ai-ml==1.18.0
      - azure-identity==1.17.0
      - azureml-core==1.53.0
      - marshmallow==3.19.0
      - xgboost==2.0.3
      - imbalanced-learn==0.11.0      # ✅ versión estable con sklearn 1.3.x
