name: dropout_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - pandas==2.2.2
      - numpy==1.26.4
      - scikit-learn==1.5.2
      - joblib==1.4.2
      - mlflow==2.16.2
      - azure-ai-ml==1.18.0
      - azure-identity==1.17.0
